### PR TITLE
Added an optional teleport delay

### PR DESCRIPTION
**Pull request by gotimo2**
added an optional, configurable teleport delay. 

Also removed a broken build.gradle dependency.

I did however not really do too much with localization, and you might want to add a perm to bypass the delay.

### CODE REVIEW

**Comment by gotimo2** [comment]
also #18 was this too

**Comment by HeroCC** [comment]
Thanks for the contribution!

**Comment by HeroCC** [comment]
I merged the PR but noticed a small issue -- players will be charged to teleport even if they move and cancel the teleport. Do you think you could make a new PR which fixes that issue @gotimo2?

**Comment by gotimo2** [comment]
https://github.com/HeroCC/BedHome/pull/28

**Pull request merged**
